/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Rigsters (https://sketchfab.com/rigsters)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/the-thinker-by-auguste-rodin-08a1e693c9674a3292dec2298b09e0ae
title: The Thinker by Auguste Rodin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/thinker.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.1, 0, 0]} rotation={[-0.01, -0.01, 0]}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials.material_0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/thinker.gltf')
